# Generated by Django 3.1.3 on 2023-06-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courier_yappy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='staatus',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=20),
        ),
    ]
