# Generated by Django 3.1.3 on 2023-06-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_staatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='staatus',
            new_name='status',
        ),
    ]
